// examples/solidjs-app/src/app.tsx
import { createSignal,createEffect } from 'solid-js';
import { wallet } from './wallet';

export default function App() {
  const TESTNET_FEDERATION_CODE =
  'fed11qgqrgvnhwden5te0v9k8q6rp9ekh2arfdeukuet595cr2ttpd3jhq6rzve6zuer9wchxvetyd938gcewvdhk6tcqqysptkuvknc7erjgf4em3zfh90kffqf9srujn6q53d6r056e4apze5cw27h75'

  const [open,setOpen]=createSignal(false)
  const [balance,setBalance]=createSignal(0);
  const [joining,setJoining]=createSignal(false)
  const [joinResult,setJoinResult]=createSignal('')
  const [joinError,setJoinError]=createSignal('')
  const [redeemResult,setRedeemResult]=createSignal('')
  const [redeemError,setRedeemError]=createSignal('')
  const [lightningResult,setLightningResult]=createSignal('')
  const [lightningError,setLightningError]=createSignal('')
  const [invoice,setInvoice]=createSignal('')
  const [error,setError]=createSignal('')
  const [generating,setGenerating]=createSignal(false)
  const [inviteCode,setInviteCode]=createSignal(TESTNET_FEDERATION_CODE)
  const [ecashInput,setEcashInput]=createSignal('')
  const [lightningInput,setLightningInput]=createSignal('')
  const [amount,setAmount]=createSignal('')
  const [description,setDescription]=createSignal('')

  const checkIsOpen=()=>{
    if(wallet.isOpen()!==open()){
      setOpen(wallet.isOpen())
    }
  }

  createEffect(()=>{
    const unsubscribe = wallet.balance.subscribeBalance((balance) => {
      checkIsOpen()
      setBalance(balance)
    })
    return () => {
      unsubscribe()
    }
  },[checkIsOpen])

  const joinFederation=async(e:Event)=>{
    e.preventDefault()
    checkIsOpen()
    console.log('Joining federation:', inviteCode)
    try {
      setJoining(true)
      const res = await wallet.joinFederation(inviteCode())
      console.log('join federation res', res)
      setJoinResult('Joined!')
    } catch (e: any) {
      console.log('Error joining federation', e)
      setJoinError(typeof e === 'object' ? e.toString() : (e as string))
    } finally {
      setJoining(false)
    }
  }

  const handleRedeem=async(e:Event)=>{
    e.preventDefault()
    try {
      const res = await wallet.mint.redeemEcash(ecashInput())
      console.log('redeem ecash res', res)
      setRedeemResult('Redeemed!')
    } catch (e) {
      console.log('Error redeeming ecash', e)
      setRedeemError(e as string)
    }
  }

  const handlePay=async(e:Event)=>{
    e.preventDefault()
    try {
      await wallet.lightning.payInvoice(lightningInput())
      setLightningResult('Paid!')
    } catch (e) {
      console.log('Error paying lightning', e)
      setLightningError(e as string)
    }
  }

  const handleGenerate=async(e:Event)=>{
    e.preventDefault()
    setGenerating(true)
    setInvoice('');
    try {
      const response = await wallet.lightning.createInvoice(
        Number(amount),
        description(),
      )
      setInvoice(response.invoice)
    } catch (e) {
      console.error('Error generating Lightning invoice', e)
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setGenerating(false)
    }
  }

  return (
    <>
      <header>
        <h1>Fedimint Typescript Library Demo</h1>

        <div class="steps">
          <strong>Steps to get started:</strong>
          <ol>
            <li>Join a Federation (persists across sessions)</li>
            <li>Generate an Invoice</li>
            <li>
              Pay the Invoice using the{' '}
              <a href="https://faucet.mutinynet.com/" target="_blank">
                mutinynet faucet
              </a>
            </li>
            <li>
              Investigate the Browser Tools
              <ul>
                <li>Browser Console for logs</li>
                <li>Network Tab (websocket) for guardian requests</li>
                <li>Application Tab for state</li>
              </ul>
            </li>
          </ol>
        </div>
      </header>
      <main>
        <div class="section">
          <h3>Wallet Status</h3>
          <div class="row">
            <strong>Is Wallet Open?</strong>
            <div>{open() ? 'Yes' : 'No'}</div>
            <button onClick={() => checkIsOpen()}>Check</button>
          </div>
          <div class="row">
            <strong>Balance:</strong>
            <div class="balance">{balance()}</div>
            sats
          </div>
        </div>

        <div class="section">
          <h3>Join Federation</h3>
          <form onSubmit={joinFederation} class="row">
            <input
              class="ecash-input"
              placeholder="Invite Code..."
              value={inviteCode()}
              onInput={(e)=>{setInviteCode(e.target.value)}}
              required
              disabled={open()}
            />
            <button type="submit" disabled={open() || joining()}>
              Join
            </button>
          </form>
          {!joinResult && open() && <i>(You've already joined a federation)</i>}
          {joinResult() && <div class="success">{joinResult()}</div>}
          {joinError() && <div class="error">{joinError()}</div>}
        </div>

        <div class="section">
          <h3>Redeem Ecash</h3>
          <form onSubmit={handleRedeem} class="row">
            <input
              placeholder="Long ecash string..."
              onInput={(e)=>{setEcashInput(e.target.value)}}
              required
            />
            <button type="submit">redeem</button>
          </form>
          {redeemResult() && <div class="success">{redeemResult()}</div>}
          {redeemError() && <div class="error">{redeemError()}</div>}
        </div>

        <div class="section">
          <h3>Pay Lightning</h3>
          <form onSubmit={handlePay} class="row">
            <input
              placeholder="lnbc..."
              onInput={(e)=>{setLightningInput(e.target.value)}}
              required
            />
            <button type="submit">pay</button>
          </form>
          {lightningResult() && <div class="success">{lightningResult()}</div>}
          {lightningError() && <div class="error">{lightningError()}</div>}
        </div>

        <div class="section">
          <h3>Generate Lightning Invoice</h3>
          <form onSubmit={handleGenerate}>
            <div class="input-group">
              <label for="amount">Amount (sats):</label>
              <input
                id="amount"
                type="number"
                placeholder="Enter amount"
                onInput={(e)=>{setAmount(e.target.value)}}
                required
              />
            </div>
            <div class="input-group">
              <label for="description">Description:</label>
              <input
                id="description"
                placeholder="Enter description"
                onInput={(e)=>{setDescription(e.target.value)}}
                required
              />
            </div>
            <button type="submit" disabled={generating()}>
              {generating() ? 'Generating...' : 'Generate Invoice'}
            </button>
          </form>
          <div>
            mutinynet faucet:{' '}
            <a href="https://faucet.mutinynet.com/" target="_blank">
              https://faucet.mutinynet.com/
            </a>
          </div>
          {invoice() && (
            <div class="success">
              <strong>Generated Invoice:</strong>
              <pre class="invoice-wrap">{invoice()}</pre>
              <button onClick={() => navigator.clipboard.writeText(invoice())}>
                Copy
              </button>
            </div>
          )}
          {error() && <div class="error">{error()}</div>}
        </div>
      </main>
    </>
  );
}

// examples/vite-core/src/App.tsx
import { useCallback, useEffect, useState } from 'react'
import { wallet } from './wallet'

const TESTNET_FEDERATION_CODE =
  'fed11qgqrgvnhwden5te0v9k8q6rp9ekh2arfdeukuet595cr2ttpd3jhq6rzve6zuer9wchxvetyd938gcewvdhk6tcqqysptkuvknc7erjgf4em3zfh90kffqf9srujn6q53d6r056e4apze5cw27h75'

// Expose the wallet to the global window object for testing
// @ts-ignore
globalThis.wallet = wallet

const useIsOpen = () => {
  const [open, setIsOpen] = useState(false)

  const checkIsOpen = useCallback(() => {
    if (open !== wallet.isOpen()) {
      setIsOpen(wallet.isOpen())
    }
  }, [open])

  useEffect(() => {
    checkIsOpen()
  }, [checkIsOpen])

  return { open, checkIsOpen }
}

const useBalance = (checkIsOpen: () => void) => {
  const [balance, setBalance] = useState(0)

  useEffect(() => {
    const unsubscribe = wallet.balance.subscribeBalance((balance: number) => {
      // checks if the wallet is open when the first
      // subscription event fires.
      // TODO: make a subscription to the wallet open status
      checkIsOpen()
      setBalance(balance)
    })

    return () => {
      unsubscribe()
    }
  }, [checkIsOpen])

  return balance
}

const App = () => {
  const { open, checkIsOpen } = useIsOpen()
  const balance = useBalance(checkIsOpen)

  return (
    <>
      <header>
        <h1>Fedimint Typescript Library Demo</h1>

        <div className="steps">
          <strong>Steps to get started:</strong>
          <ol>
            <li>Join a Federation (persists across sessions)</li>
            <li>Generate an Invoice</li>
            <li>
              Pay the Invoice using the{' '}
              <a href="https://faucet.mutinynet.com/" target="_blank">
                mutinynet faucet
              </a>
            </li>
            <li>
              Investigate the Browser Tools
              <ul>
                <li>Browser Console for logs</li>
                <li>Network Tab (websocket) for guardian requests</li>
                <li>Application Tab for state</li>
              </ul>
            </li>
          </ol>
        </div>
      </header>
      <main>
        <WalletStatus open={open} checkIsOpen={checkIsOpen} balance={balance} />
        <JoinFederation open={open} checkIsOpen={checkIsOpen} />
        <GenerateLightningInvoice />
        <RedeemEcash />
        <SendLightning />
      </main>
    </>
  )
}

const WalletStatus = ({
  open,
  checkIsOpen,
  balance,
}: {
  open: boolean
  checkIsOpen: () => void
  balance: number
}) => {
  return (
    <div className="section">
      <h3>Wallet Status</h3>
      <div className="row">
        <strong>Is Wallet Open?</strong>
        <div>{open ? 'Yes' : 'No'}</div>
        <button onClick={() => checkIsOpen()}>Check</button>
      </div>
      <div className="row">
        <strong>Balance:</strong>
        <div className="balance">{balance}</div>
        sats
      </div>
    </div>
  )
}

const JoinFederation = ({
  open,
  checkIsOpen,
}: {
  open: boolean
  checkIsOpen: () => void
}) => {
  const [inviteCode, setInviteCode] = useState(TESTNET_FEDERATION_CODE)
  const [joinResult, setJoinResult] = useState<string | null>(null)
  const [joinError, setJoinError] = useState('')
  const [joining, setJoining] = useState(false)

  const joinFederation = async (e: React.FormEvent) => {
    e.preventDefault()
    checkIsOpen()

    console.log('Joining federation:', inviteCode)
    try {
      setJoining(true)
      const res = await wallet.joinFederation(inviteCode)
      console.log('join federation res', res)
      setJoinResult('Joined!')
      setJoinError('')
    } catch (e: any) {
      console.log('Error joining federation', e)
      setJoinError(typeof e === 'object' ? e.toString() : (e as string))
      setJoinResult('')
    } finally {
      setJoining(false)
    }
  }

  return (
    <div className="section">
      <h3>Join Federation</h3>
      <form onSubmit={joinFederation} className="row">
        <input
          className="ecash-input"
          placeholder="Invite Code..."
          required
          value={inviteCode}
          onChange={(e) => setInviteCode(e.target.value)}
          disabled={open}
        />
        <button type="submit" disabled={open || joining}>
          Join
        </button>
      </form>
      {!joinResult && open && <i>(You've already joined a federation)</i>}
      {joinResult && <div className="success">{joinResult}</div>}
      {joinError && <div className="error">{joinError}</div>}
    </div>
  )
}

const RedeemEcash = () => {
  const [ecashInput, setEcashInput] = useState('')
  const [redeemResult, setRedeemResult] = useState('')
  const [redeemError, setRedeemError] = useState('')

  const handleRedeem = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      const res = await wallet.mint.redeemEcash(ecashInput)
      console.log('redeem ecash res', res)
      setRedeemResult('Redeemed!')
      setRedeemError('')
    } catch (e) {
      console.log('Error redeeming ecash', e)
      setRedeemError(e as string)
      setRedeemResult('')
    }
  }

  return (
    <div className="section">
      <h3>Redeem Ecash</h3>
      <form onSubmit={handleRedeem} className="row">
        <input
          placeholder="Long ecash string..."
          required
          value={ecashInput}
          onChange={(e) => setEcashInput(e.target.value)}
        />
        <button type="submit">redeem</button>
      </form>
      {redeemResult && <div className="success">{redeemResult}</div>}
      {redeemError && <div className="error">{redeemError}</div>}
    </div>
  )
}

const SendLightning = () => {
  const [lightningInput, setLightningInput] = useState('')
  const [lightningResult, setLightningResult] = useState('')
  const [lightningError, setLightningError] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      await wallet.lightning.payInvoice(lightningInput)
      setLightningResult('Paid!')
      setLightningError('')
    } catch (e) {
      console.log('Error paying lightning', e)
      setLightningError(e as string)
      setLightningResult('')
    }
  }

  return (
    <div className="section">
      <h3>Pay Lightning</h3>
      <form onSubmit={handleSubmit} className="row">
        <input
          placeholder="lnbc..."
          required
          value={lightningInput}
          onChange={(e) => setLightningInput(e.target.value)}
        />
        <button type="submit">pay</button>
      </form>
      {lightningResult && <div className="success">{lightningResult}</div>}
      {lightningError && <div className="error">{lightningError}</div>}
    </div>
  )
}

const GenerateLightningInvoice = () => {
  const [amount, setAmount] = useState('')
  const [description, setDescription] = useState('')
  const [invoice, setInvoice] = useState('')
  const [error, setError] = useState('')
  const [generating, setGenerating] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setInvoice('')
    setError('')
    setGenerating(true)
    try {
      const response = await wallet.lightning.createInvoice(
        Number(amount),
        description,
      )
      setInvoice(response.invoice)
    } catch (e) {
      console.error('Error generating Lightning invoice', e)
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div className="section">
      <h3>Generate Lightning Invoice</h3>
      <form onSubmit={handleSubmit}>
        <div className="input-group">
          <label htmlFor="amount">Amount (sats):</label>
          <input
            id="amount"
            type="number"
            placeholder="Enter amount"
            required
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
          />
        </div>
        <div className="input-group">
          <label htmlFor="description">Description:</label>
          <input
            id="description"
            placeholder="Enter description"
            required
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
        </div>
        <button type="submit" disabled={generating}>
          {generating ? 'Generating...' : 'Generate Invoice'}
        </button>
      </form>
      <div>
        mutinynet faucet:{' '}
        <a href="https://faucet.mutinynet.com/" target="_blank">
          https://faucet.mutinynet.com/
        </a>
      </div>
      {invoice && (
        <div className="success">
          <strong>Generated Invoice:</strong>
          <pre className="invoice-wrap">{invoice}</pre>
          <button onClick={() => navigator.clipboard.writeText(invoice)}>
            Copy
          </button>
        </div>
      )}
      {error && <div className="error">{error}</div>}
    </div>
  )
}

export default App
